# .github/workflows/deploy-to-firebase-hosting.yml

name: Deploy to Firebase Hosting

# 工作流程触发条件：当有代码推送到 main 分支时触发
on:
  push:
    branches:
      - main  # 或者你的主分支名称，如 master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest # 使用最新的 Ubuntu 运行环境

    steps:
      # 第1步：检出你的仓库代码
      - name: Checkout repository
        uses: actions/checkout@v3 # 使用官方的 checkout action

      # 第2步：设置 Node.js 环境 (Firebase CLI 需要)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # 指定 Node.js 版本，建议使用 LTS 版本

      # # 第3步：安装 Firebase CLI
      # # 如果你的项目有其他构建步骤或依赖，可以在这里添加 npm install 等
      # - name: Install Firebase CLI
      #   run: npm install -g firebase-tools

      # # 第4步：部署到 Firebase Hosting
      # - name: Deploy to Firebase Hosting
      #   env:
      #     FIREBASE_CLI_PREVIEWS: hostingchannels # 可选，如果使用预览频道
      #     FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }} # 备选方案：使用 FIREBASE_TOKEN
      #     GOOGLE_APPLICATION_CREDENTIALS: service-account.json # 临时文件名
      #   run: |
      #     echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}' > service-account.json
      #     firebase deploy --only hosting --project ${{ secrets.FIREBASE_PROJECT_ID || vars.FIREBASE_PROJECT_ID }} --non-interactive --token "${{ secrets.FIREBASE_TOKEN }}"
      #     # 注意: 上面的 --token 参数是备选，如果 FIREBASE_SERVICE_ACCOUNT_JSON 设置正确，
      #     # Firebase CLI 通常会自动使用 GOOGLE_APPLICATION_CREDENTIALS。
      #     # 如果只用服务账户，可以简化为：
      #     # firebase deploy --only hosting --project ${{ secrets.FIREBASE_PROJECT_ID }} --non-interactive

    # 如果你更倾向于使用 Firebase 官方提供的 GitHub Action (推荐)
    # 可以替换上面的第3步和第4步为：
      - name: Deploy to Firebase Hosting using FirebaseExtended Action
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}' # GITHUB_TOKEN 是自动提供的
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}'
          channelId: live # 部署到实时频道，也可以是预览频道 ID
          projectId: ${{ secrets.FIREBASE_PROJECT_ID }} # 你的 Firebase 项目 I